### ISSUE TITLE
boyfriendlist is sexist

### ISSUE THREAD

**Issue by guluarte** [endingwithali/boyfriendlist#31]
what every coding project needs is a healthy dose of patriarchal ownership and a strong reminder that women’s contributions are just ‘helping out’ the real MVPs. I mean, who doesn’t love a repo named ‘boyfriendlist’ where men can keep track of their favorite coding projects while simultaneously keeping tabs on their girlfriends’ to-do lists? It’s not like it perpetuates harmful gender stereotypes or anything #NotMyRepo

**Comment by Zorlin** [comment]
overthinking

**Comment by guluarte** [comment]
it was sarcasm

**Comment by endingwithali** [comment]
anyone of any gender can join the boyfriend list. 


nonissue, closed.
