### ISSUE TITLE
Needs a Wall of Ex-Boyfriends or a Wall of shame with the crime they have committed 

### ISSUE THREAD

**Issue by electric-sheep-ree** [endingwithali/boyfriendlist#53]
IE

# Wall of Shame

<ul>
<li><a href="https://x.com/ElectricSheep54/"</a>Electric Sheep</li>
<ul>
<li>Twitter Reply Guy</li>
<li>simps for other people on Twitter besides Ali</li>
</ul>
</ul>

**Comment by endingwithali** [comment]
wall of shame is only for people who try to mess with the boyfriend list. 

included in TOP BULLIES list
