### ISSUE TITLE
Additional Documentation

### ISSUE THREAD

**Issue by williamgkzhang** [endingwithali/boyfriendlist#62]
I saw one of my co-boyfriends added a slide show in a PR so I thought I'd make a little website.  Didn't need to commit anything so I figured an issue would work.

Additional documentation: 
[Dating profile website](https://datingprofile.williamgkzhang.me/)

**Comment by igorbrigadir** [comment]
LGTM!

**Comment by endingwithali** [comment]
pls redo ur pr and include the link thank you
