### ISSUE TITLE
grilled cheese

### ISSUE THREAD

**Issue by RandomTypek** [endingwithali/boyfriendlist#63]
![vgm62vl48hv71](https://github.com/endingwithali/boyfriendlist/assets/31035586/9ae44d20-b856-4504-aa9c-94751e47dccf)

**Comment by igorbrigadir** [comment]
LGTM!

**Comment by endingwithali** [comment]
excellent. will include in next release. this is really important <3

**Comment by RandomTypek** [comment]
hahah thank you m'lady
